name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Update
      run: sudo apt update && sudo apt full-upgrade -y -o "Dpkg::Options::=--force-confold" && sudo apt autoremove -y --purge
    - name: Build
      run: cargo build --verbose --release
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
       name: bin
       path: target/release/
